package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemStockEntity;
import org.apache.ibatis.annotations.Param;

public interface ItemStockEntityMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Tue Feb 12 20:29:46 CST 2019
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Tue Feb 12 20:29:46 CST 2019
   */
  int insert(ItemStockEntity record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Tue Feb 12 20:29:46 CST 2019
   */
  int insertSelective(ItemStockEntity record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Tue Feb 12 20:29:46 CST 2019
   */
  ItemStockEntity selectByPrimaryKey(Integer id);

  ItemStockEntity selectByItemId(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Tue Feb 12 20:29:46 CST 2019
   */
  int updateByPrimaryKeySelective(ItemStockEntity record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Tue Feb 12 20:29:46 CST 2019
   */
  int updateByPrimaryKey(ItemStockEntity record);

  int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}