package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.OrderInfoEntity;

public interface OrderInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Feb 16 20:35:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Feb 16 20:35:32 CST 2019
     */
    int insert(OrderInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Feb 16 20:35:32 CST 2019
     */
    int insertSelective(OrderInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Feb 16 20:35:32 CST 2019
     */
    OrderInfoEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Feb 16 20:35:32 CST 2019
     */
    int updateByPrimaryKeySelective(OrderInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Feb 16 20:35:32 CST 2019
     */
    int updateByPrimaryKey(OrderInfoEntity record);
}