package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.PromoEntity;

public interface PromoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Feb 20 21:47:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Feb 20 21:47:43 CST 2019
     */
    int insert(PromoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Feb 20 21:47:43 CST 2019
     */
    int insertSelective(PromoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Feb 20 21:47:43 CST 2019
     */
    PromoEntity selectByPrimaryKey(Integer id);

    PromoEntity selectByItemId(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Feb 20 21:47:43 CST 2019
     */
    int updateByPrimaryKeySelective(PromoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Feb 20 21:47:43 CST 2019
     */
    int updateByPrimaryKey(PromoEntity record);
}