package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.SequenceInfoEntity;

public interface SequenceInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Feb 17 18:54:41 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Feb 17 18:54:41 CST 2019
     */
    int insert(SequenceInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Feb 17 18:54:41 CST 2019
     */
    int insertSelective(SequenceInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Feb 17 18:54:41 CST 2019
     */
    SequenceInfoEntity selectByPrimaryKey(String name);

    SequenceInfoEntity getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Feb 17 18:54:41 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Feb 17 18:54:41 CST 2019
     */
    int updateByPrimaryKey(SequenceInfoEntity record);
}