package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserPasswordEntity;

public interface UserPasswordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jan 13 00:21:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jan 13 00:21:31 CST 2019
     */
    int insert(UserPasswordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jan 13 00:21:31 CST 2019
     */
    int insertSelective(UserPasswordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jan 13 00:21:31 CST 2019
     */
    UserPasswordEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jan 13 00:21:31 CST 2019
     */
    int updateByPrimaryKeySelective(UserPasswordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jan 13 00:21:31 CST 2019
     */
    int updateByPrimaryKey(UserPasswordEntity record);
}